gesdinet_jwt_refresh_token:
    refresh_token_class: App\User\Infrastructure\Security\RefreshToken
    ttl: '%env(int:JWT_REFRESH_TTL)%'
    ttl_update: true
    single_use: true
    cookie:
        enabled: false
    return_expiration: true
